version: '3.8'

services:
  delivery-db:
    container_name: delivery-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: orders_delivery
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  courier-db:
    container_name: courier-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: courier_service
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - courier-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  delivery-service:
    build:
      context: ./delivery
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@delivery-db:5432/orders_delivery
      - RABBITMQ_URL=amqp://51.250.26.59:5672
    depends_on:
      - delivery-db

  courier-service:
    build:
      context: ./courier
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@courier-db:5432/courier_service
      - RABBITMQ_URL=amqp://51.250.26.59:5672
    depends_on:
      - courier-db

volumes:
  delivery-db-data:
    driver: local
  courier-db-data:
    driver: local